# fly.toml app configuration file generated for kylemcd-dot-com on 2025-10-06T14:58:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kylemcd-dot-com'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
