/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsesIndexRouteImport } from './routes/uses.index'
import { Route as ReadingIndexRouteImport } from './routes/reading.index'
import { Route as RacingIndexRouteImport } from './routes/racing.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as ListeningIndexRouteImport } from './routes/listening.index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesIndexRoute = UsesIndexRouteImport.update({
  id: '/uses/',
  path: '/uses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingIndexRoute = ReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacingIndexRoute = RacingIndexRouteImport.update({
  id: '/racing/',
  path: '/racing/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningIndexRoute = ListeningIndexRouteImport.update({
  id: '/listening/',
  path: '/listening/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/listening/': typeof ListeningIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/racing/': typeof RacingIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/uses/': typeof UsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/listening': typeof ListeningIndexRoute
  '/posts': typeof PostsIndexRoute
  '/racing': typeof RacingIndexRoute
  '/reading': typeof ReadingIndexRoute
  '/uses': typeof UsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/listening/': typeof ListeningIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/racing/': typeof RacingIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/uses/': typeof UsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts/$slug'
    | '/listening/'
    | '/posts/'
    | '/racing/'
    | '/reading/'
    | '/uses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/$slug'
    | '/listening'
    | '/posts'
    | '/racing'
    | '/reading'
    | '/uses'
  id:
    | '__root__'
    | '/'
    | '/posts/$slug'
    | '/listening/'
    | '/posts/'
    | '/racing/'
    | '/reading/'
    | '/uses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ListeningIndexRoute: typeof ListeningIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  RacingIndexRoute: typeof RacingIndexRoute
  ReadingIndexRoute: typeof ReadingIndexRoute
  UsesIndexRoute: typeof UsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses/': {
      id: '/uses/'
      path: '/uses'
      fullPath: '/uses/'
      preLoaderRoute: typeof UsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/': {
      id: '/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racing/': {
      id: '/racing/'
      path: '/racing'
      fullPath: '/racing/'
      preLoaderRoute: typeof RacingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening/': {
      id: '/listening/'
      path: '/listening'
      fullPath: '/listening/'
      preLoaderRoute: typeof ListeningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsSlugRoute: PostsSlugRoute,
  ListeningIndexRoute: ListeningIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  RacingIndexRoute: RacingIndexRoute,
  ReadingIndexRoute: ReadingIndexRoute,
  UsesIndexRoute: UsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
